models:
  - name: fact_order_items
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - order_id
            - order_item_id
            - product_id
            - seller_id
            - shipping_limit_date
            - price
            - freight_value
    columns:
      - name: order_item_sk
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - not_null

  - name: fact_order_payments
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - order_id
            - payment_sequential
            - payment_type
            - payment_installments
            - payment_value
    columns:
      - name: order_payment_sk
        tests: 
          - unique
          - not_null
      - name: order_id
        tests:
          - not_null

  - name: fact_order_reviews
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - review_id
            - order_id
            - review_score
            - review_creation_date
            - review_answer_timestamp
    columns:
      - name: order_review_sk
        tests:
          - unique
          - not_null
      - name: review_id
        tests:
          - not_null